# Generated by Django 5.0.4 on 2026-02-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('room_type', models.CharField(choices=[('singola', 'Camera Singola'), ('doppia', 'Camera Doppia'), ('matrimoniale', 'Camera Matrimoniale'), ('junior_suite', 'Junior Suite'), ('panoramica', 'Suite Panoramica'), ('casale', 'Casale')], default='singola', max_length=20, verbose_name='Room Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per Night')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Capacity (guests)')),
                ('size_sqm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Room Size (m²)')),
                ('bed_type', models.CharField(blank=True, max_length=100, verbose_name='Bed Type')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Floor')),
                ('view', models.CharField(blank=True, max_length=100, verbose_name='View')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcony')),
                ('has_terrace', models.BooleanField(default=False, verbose_name='Terrace')),
                ('has_air_con', models.BooleanField(default=True, verbose_name='Air Conditioning')),
                ('has_minibar', models.BooleanField(default=False, verbose_name='Mini Bar')),
                ('has_safe', models.BooleanField(default=True, verbose_name='Safe')),
                ('has_bathrobe', models.BooleanField(default=False, verbose_name='Bathrobe')),
                ('is_pet_friendly', models.BooleanField(default=False, verbose_name='Pet Friendly')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='Accessible')),
                ('is_non_smoking', models.BooleanField(default=True, verbose_name='Non Smoking')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Booking')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_type', 'price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
