# Generated by Django 5.0.4 on 2026-03-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(choices=[('starter', 'Antipasti'), ('pasta', 'Primi Piatti'), ('main', 'Secondi Piatti'), ('side', 'Contorni'), ('dessert', 'Dolci'), ('drink', 'Bevande'), ('wine', 'Vini')], default='starter', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Photo')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegan')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Gluten Free')),
                ('is_signature', models.BooleanField(default=False, verbose_name='Signature Dish')),
                ('is_seasonal', models.BooleanField(default=False, verbose_name='Seasonal')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
