# Generated by Django 5.0.4 on 2026-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_open', models.TimeField(default='12:30', verbose_name='Lunch Opening Time')),
                ('lunch_close', models.TimeField(default='14:30', verbose_name='Lunch Closing Time')),
                ('lunch_enabled', models.BooleanField(default=True, verbose_name='Lunch Service Active')),
                ('dinner_open', models.TimeField(default='19:30', verbose_name='Dinner Opening Time')),
                ('dinner_close', models.TimeField(default='22:30', verbose_name='Dinner Closing Time')),
                ('dinner_enabled', models.BooleanField(default=True, verbose_name='Dinner Service Active')),
                ('closed_monday', models.BooleanField(default=True, verbose_name='Closed Monday')),
                ('closed_tuesday', models.BooleanField(default=False, verbose_name='Closed Tuesday')),
                ('closed_wednesday', models.BooleanField(default=False, verbose_name='Closed Wednesday')),
                ('closed_thursday', models.BooleanField(default=False, verbose_name='Closed Thursday')),
                ('closed_friday', models.BooleanField(default=False, verbose_name='Closed Friday')),
                ('closed_saturday', models.BooleanField(default=False, verbose_name='Closed Saturday')),
                ('closed_sunday', models.BooleanField(default=False, verbose_name='Closed Sunday')),
                ('closed_note', models.CharField(blank=True, help_text='Optional note shown under hours, e.g. "Closed in August"', max_length=120, verbose_name='Closing Note')),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
