# Generated by Django 5.0.4 on 2026-02-28 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('guest_phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('check_in', models.DateField(verbose_name='Check-in Date')),
                ('check_out', models.DateField(verbose_name='Check-out Date')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Number of Guests')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per Night')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Booking Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Booking',
                'verbose_name_plural': 'Room Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
