# Generated by Django 5.0.4 on 2026-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('guest_phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_slot', models.CharField(choices=[('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30')], default='19:30', max_length=10, verbose_name='Time')),
                ('guests', models.PositiveIntegerField(default=2, verbose_name='Number of Guests')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Booking Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table Booking',
                'verbose_name_plural': 'Table Bookings',
                'ordering': ['-date', 'time_slot'],
            },
        ),
    ]
