# Generated by Django 5.0.4 on 2026-03-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_tablebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('room_confirmation', 'Room Booking Confirmation'), ('table_confirmation', 'Table Booking Confirmation')], max_length=50, unique=True, verbose_name='Template')),
                ('subject', models.CharField(help_text='Available variables: {{ reference }}, {{ guest_name }}, {{ room_name }}, {{ check_in }}, {{ check_out }}, {{ nights }}, {{ guests }}, {{ total_price }}, {{ date }}, {{ time_slot }}, {{ service }}', max_length=200, verbose_name='Subject')),
                ('body', models.TextField(help_text='Plain text email body. Same variables as subject are available.', verbose_name='Body')),
                ('is_active', models.BooleanField(default=True, help_text='If inactive, the default file template will be used instead.', verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
    ]
