# Generated by Django 5.0.4 on 2026-03-18 21:13

from django.db import migrations


def seed_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('bookings', 'EmailTemplate')

    EmailTemplate.objects.get_or_create(
        key='room_confirmation',
        defaults={
            'subject': 'Conferma Prenotazione {{ reference }} — Hotel Santa Filomena',
            'body': (
                "Gentile {{ guest_name }},\n\n"
                "La sua prenotazione è stata confermata.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "DETTAGLI PRENOTAZIONE\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "Numero di riferimento : {{ reference }}\n"
                "Camera                : {{ room_name }}\n"
                "Check-in              : {{ check_in }}\n"
                "Check-out             : {{ check_out }}\n"
                "Notti                 : {{ nights }}\n"
                "Ospiti                : {{ guests }}\n"
                "Prezzo per notte      : €{{ price_per_night }}\n"
                "Totale                : €{{ total_price }}\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "{% if special_requests %}Richieste speciali: {{ special_requests }}\n\n{% endif %}"
                "Per qualsiasi informazione:\n"
                "Email : info@santafilomena.com\n"
                "Tel   : +39 06 1234 5678\n\n"
                "Grazie per aver scelto Hotel Santa Filomena.\n\n"
                "— Il Team di Hotel Santa Filomena"
            ),
            'is_active': True,
        }
    )

    EmailTemplate.objects.get_or_create(
        key='table_confirmation',
        defaults={
            'subject': 'Conferma Prenotazione Tavolo {{ reference }} — Ristorante Santa Filomena',
            'body': (
                "Gentile {{ guest_name }},\n\n"
                "La sua prenotazione al ristorante è stata confermata.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "DETTAGLI PRENOTAZIONE\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "Numero di riferimento : {{ reference }}\n"
                "Data                  : {{ date }}\n"
                "Orario                : {{ time_slot }}\n"
                "Servizio              : {{ service }}\n"
                "Ospiti                : {{ guests }}\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
                "{% if special_requests %}Richieste speciali: {{ special_requests }}\n\n{% endif %}"
                "In caso di imprevisti, avvisarci almeno 24 ore prima.\n\n"
                "Email : info@santafilomena.com\n"
                "Tel   : +39 06 1234 5678\n\n"
                "— Il Team di Hotel Santa Filomena"
            ),
            'is_active': True,
        }
    )


def unseed_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('bookings', 'EmailTemplate')
    EmailTemplate.objects.filter(
        key__in=['room_confirmation', 'table_confirmation']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_emailtemplate'),
    ]

    operations = [
    ]
